version: "2.0"
services:
  choralweb:
    build: .
    command: npm run-script start
    restart: always
    ports:
      - "80:3000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      REDIS_STORE_URI: "redis://redis:6379"
      REDIS_STORE_SECRET: "DEVELOPMENT_SECRET"
      MONGO_URL: "mongodb://mongodb:27017"
      CASSANDRA_URL: "cassandra"
    external_links:
      - redis
      - cassandra
  choralworker:
    build: .
    command: npm run-script start-worker
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      REDIS_STORE_URI: "redis://redis:6379"
      MONGO_URL: "mongodb://mongodb:27017"
      UPDATE_NEW_CHORALS: "3000"
      ALLEGRO_URL: "http://172.18.2.102:8081/"
    external_links:
      - redis
  mongodb:
    image: mongo:latest
    container_name: "mongo_db"
    environment:
      - MONGO_DATA_DIR=/data/db
      # do not keep track of the logs
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    restart: always

networks:
  default:
    external:
      name: choralstorm
